import { AppError } from '../utils/app-error.js';
import { generateId } from '../utils/id.js';
import { createRoadmapSchema } from '../schemas/roadmap.schema.js';
import { findDiagnosticResultById } from '../repositories/diagnostic.repository.js';
import { createRoadmap, findRoadmapByDiagnosticResultId, findRoadmapById, updateRoadmapStatus } from '../repositories/roadmap.repository.js';
import { createManyTasks, findTasksByRoadmapId } from '../repositories/task.repository.js';
import { buildRoadmapTasks, buildRoadmapTitle } from './roadmap-generation.service.js';
export async function createRoadmapFromDiagnostic(payload){const parsed=createRoadmapSchema.parse(payload);const diagnostic=await findDiagnosticResultById(parsed.diagnosticResultId);if(!diagnostic){throw new AppError('Diagnostic result not found.',404);}const existing=await findRoadmapByDiagnosticResultId(parsed.diagnosticResultId);if(existing){throw new AppError('A roadmap has already been generated for this diagnostic result.',409);}const roadmapId=generateId();const roadmap={id:roadmapId,diagnosticResultId:parsed.diagnosticResultId,title:buildRoadmapTitle(diagnostic.userName),status:'active',createdAt:new Date().toISOString()};const tasks=await buildRoadmapTasks(roadmapId,diagnostic.scores);await createRoadmap(roadmap);await createManyTasks(tasks);return {...roadmap,progress:{totalTasks:tasks.length,completedTasks:0,completionPercentage:0}};}
export async function getRoadmapWithProgress(id){const roadmap=await findRoadmapById(id);if(!roadmap){throw new AppError('Roadmap not found.',404);}const tasks=await findTasksByRoadmapId(id);const completedTasks=tasks.filter((task)=>task.status==='completed').length;const totalTasks=tasks.length;const completionPercentage=totalTasks===0?0:Math.round((completedTasks/totalTasks)*100);const nextStatus=totalTasks>0&&completedTasks===totalTasks?'completed':'active';if(roadmap.status!==nextStatus){await updateRoadmapStatus(roadmap.id,nextStatus);}return {...roadmap,status:nextStatus,progress:{totalTasks,completedTasks,completionPercentage}};}
export async function listRoadmapTasks(roadmapId){const roadmap=await findRoadmapById(roadmapId);if(!roadmap){throw new AppError('Roadmap not found.',404);}return findTasksByRoadmapId(roadmapId);}
